### ISSUE TITLE
aggregate TALSH stats

### ISSUE THREAD

**Issue by ajaypanyala** [DmitryLyakh/TAL_SH#7]
Currently calling talshstats() at the end of a large multi-node run (using all available GPUs per node) dumps the stats for every GPU. Can we have a mechanism to aggregate the stats (flop count, etc) instead of dumping the stats for every GPU?

Thanks
Ajay

**Comment by DmitryLyakh** [comment]
talshStats() will now also print the aggregate flop count and data volume transferred across all GPU devices used by the process. Check out the master branch.
